services:
  - type: web
    name: casualtalks-backend
    env: node
    buildCommand: npm ci --production
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /
